# Template for running nmap on a target/list of targets
name: Nmap Scanner

# add your `on` trigger statement if required
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update the packages
        run: sudo apt-get update -y

      - name: Install nmap
        run: sudo apt-get install -y nmap

      - name: Run nmap on a set of targets
        run: |
          sudo {command}

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: Commit nmap results
          commit_user_name: 'Nmap Runner'
          commit_user_email: 'github-actions.nmap@github.com'