name: Nmap Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update the packages
        run: sudo apt-get update -y

      - name: Install masscan
        run: sudo apt-get install -y nmap

      - name: Run masscan on a set of targets
        run: {command}

      # github doesn't allow you to commit files > 100M
      - name: Pruning files greater than 100MB
        run: find . -size +99M -delete

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: Commit nmap results
          commit_user_name: 'Nmap Runner'
          commit_user_email: 'github-actions.nmap@github.com'